org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.caching.debug=false
#org.gradle.configureondemand=true

mod.id=zeus
mod.name=Zeus
mod.version=1.0.0
mod.group=dev.zeus
mod.description=Lets resource packs replace Athena CTM (e.g. Chipped) with Fusion; live Fusion item biome tint and loader debug probes.

