org.gradle.jvmargs=-Xmx8G
org.gradle.parallel=false
org.gradle.caching=false
org.gradle.caching.debug=false
#org.gradle.configureondemand=true

mod.id=zeus
mod.name=Zeus
mod.version=0.1.0
mod.group=dev.zeus
mod.description=Remount Athena CTM blocks (e.g. Chipped) onto Fusion or other CTM backends.

