modLoader = "javafml"
loaderVersion = "*"
issueTrackerURL = "https://github.com/meza/Stonecraft/issues"
license = "MIT"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
authors = "minerguy341"
description = '''
${description}
'''
logoFile = "assets/${id}/icon.png"
logoBlur = false

[[dependencies.${id}]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraftVersion},)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "athena"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "fusion"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[dependencies.${id}]]
modId = "chipped"
type = "optional"
versionRange = "*"
ordering = "NONE"
side = "CLIENT"

[[mixins]]
config = "zeus.mixins.json"
